import "dotenv/config";
import fs from "node:fs/promises";
import path from "node:path";
import jwt from "jsonwebtoken";
import mysql from "mysql2/promise";
import { chromium } from "playwright-core";

const db = await mysql.createConnection({ host: process.env.MYSQL_HOST, port: Number(process.env.MYSQL_PORT), user: process.env.MYSQL_USER, password: process.env.MYSQL_PASSWORD, database: process.env.MYSQL_DATABASE });
const [rows] = await db.query("SELECT u.id,u.employee_id employeeId,u.email,COALESCE(e.employee_name,u.email) name FROM app_users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id LEFT JOIN employees e ON e.id=u.employee_id WHERE r.normalized_name='ADMIN' AND u.is_active=TRUE LIMIT 1");
const user = rows[0];
const [branches] = await db.execute("SELECT branch_id id FROM user_branches WHERE user_id=? UNION SELECT branch_id id FROM app_users WHERE id=? AND branch_id IS NOT NULL", [user.id, user.id]);
await db.end();
const profile = { id:Number(user.id), employeeId:user.employeeId ? Number(user.employeeId) : null, name:user.name, email:user.email, role:"ADMIN", roles:["ADMIN"], branchIds:branches.map(row => Number(row.id)) };
const token = jwt.sign(profile, process.env.JWT_SECRET, { expiresIn:"10m" });
const browser = await chromium.launch({ headless:true, executablePath:"C:/Program Files/Google/Chrome/Application/chrome.exe" });
const page = await browser.newPage({ viewport:{ width:1142, height:779 }, deviceScaleFactor:1 });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
await page.addInitScript(({ token, profile }) => { localStorage.setItem("crm_token", token); localStorage.setItem("crm_user", JSON.stringify(profile)); }, { token, profile });
await page.goto("http://localhost:3000/leads", { waitUntil:"networkidle" });
await page.getByRole("button", { name:/Create funnel/i }).click();
await page.locator(".filter-workspace").waitFor();
await page.locator(".filter-sections>button").nth(1).click();
await page.locator(".filter-sections>button").first().click();
const artifactDirectory = path.resolve("artifacts");
await fs.mkdir(artifactDirectory, { recursive:true });
const screenshot = path.join(artifactDirectory, "filter-workspace-qa.png");
await page.screenshot({ path:screenshot, fullPage:true });
await page.locator(".filter-workspace-footer>.filter-save-name").fill("QA Funnel");
await page.getByRole("button", { name:/Save funnel/i }).click();
await page.locator(".filter-chip-row em").waitFor();
await page.getByRole("button", { name:/Apply filter/i }).click();
await page.locator(".filter-workspace").waitFor({ state:"detached" });
await page.locator('button[title="Open filters"]').click();
await page.locator(".filter-workspace").waitFor();
const options = await page.locator(".saved-filter-loader option").allTextContents();
const saved = options.some(option => option.includes("QA Funnel"));
console.log(JSON.stringify({ screenshot, viewport:"1142x779", createFunnelOpens:true, filterButtonOpens:true, categorySwitching:true, applyCloses:true, savedFilterReloads:saved, consoleErrors:errors.filter(error => !error.includes("404")) }, null, 2));
await browser.close();
