CREATE TABLE IF NOT EXISTS crm_jodo_payment_links (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  business_unit_id BIGINT UNSIGNED NOT NULL,
  branch_id BIGINT UNSIGNED NOT NULL,
  lead_id BIGINT UNSIGNED NULL,
  environment ENUM('production','uat') NOT NULL DEFAULT 'production',
  order_id VARCHAR(120) NOT NULL,
  redirect_url VARCHAR(1000) NOT NULL,
  payer_name VARCHAR(200) NOT NULL,
  payer_phone VARCHAR(30) NOT NULL,
  payer_email VARCHAR(254) NOT NULL,
  student_name VARCHAR(200) NULL,
  identifier VARCHAR(120) NULL,
  custom_identifier VARCHAR(120) NULL,
  grade VARCHAR(120) NULL,
  academic_year_start SMALLINT UNSIGNED NULL,
  academic_year_end SMALLINT UNSIGNED NULL,
  expires_at_utc DATETIME(6) NULL,
  amount DECIMAL(12,2) NOT NULL,
  details_json JSON NOT NULL,
  notes_json JSON NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'unpaid',
  transaction_id VARCHAR(150) NULL,
  paid_at_utc DATETIME(6) NULL,
  settled_at_utc DATETIME(6) NULL,
  settlement_utr VARCHAR(150) NULL,
  raw_response JSON NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  created_at_utc DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at_utc DATETIME(6) NULL ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_jodo_payment_link_order (environment,order_id),
  KEY ix_jodo_link_bu_status (business_unit_id,status,created_at_utc),
  KEY ix_jodo_link_branch (branch_id,created_at_utc),
  KEY ix_jodo_link_lead (lead_id,created_at_utc),
  CONSTRAINT fk_jodo_link_bu FOREIGN KEY (business_unit_id) REFERENCES crm_business_units(id) ON DELETE CASCADE,
  CONSTRAINT fk_jodo_link_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT fk_jodo_link_lead FOREIGN KEY (lead_id) REFERENCES crm_leads(id) ON DELETE SET NULL,
  CONSTRAINT fk_jodo_link_user FOREIGN KEY (created_by_user_id) REFERENCES app_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
