import { useEffect, useRef, useState } from 'react';
import { Copy, Mail, Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { api } from '../api';

const categories = ['Lead','Follow-up','Application','Admission','Payment','General','Other'];
const variables = ['student_name','parent_name','lead_name','branch_name','class_name','counsellor_name','counsellor_phone','application_number','application_date','followup_date','company_name'];
const blank = { templateName:'', category:'General', subject:'', bodyHtml:'', status:'ACTIVE' };

export default function EmailTemplatesSettings({ onMessage }) {
  const [templates,setTemplates]=useState([]), [search,setSearch]=useState(''), [status,setStatus]=useState(''), [category,setCategory]=useState('');
  const [editing,setEditing]=useState(null), [loading,setLoading]=useState(true), [error,setError]=useState('');
  const load=async()=>{setLoading(true);try{const q=new URLSearchParams();if(search)q.set('search',search);if(status)q.set('status',status);if(category)q.set('category',category);const result=await api.get(`/email/templates?${q}`);setTemplates(result.data||[]);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}};
  useEffect(()=>{const id=setTimeout(load,200);return()=>clearTimeout(id);},[search,status,category]);
  const action=async(fn,message)=>{try{await fn();onMessage?.({type:'success',text:message});await load();}catch(e){setError(e.message);}};
  return <main className="p-6 md:p-9 space-y-6">
    <header className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="p-2.5 rounded-xl bg-primary-50 text-primary-600"><Mail size={22}/></span><div><h1 className="text-2xl font-bold">Email Templates</h1><p className="text-sm text-secondary-600 mt-1">Create reusable messages with CRM merge fields.</p></div></div><button className="btn btn-primary" onClick={()=>setEditing({...blank})}><Plus size={17}/> Create Template</button></header>
    {error&&<div className="p-3 rounded-lg border border-red-200 bg-red-50 text-red-700 text-sm">{error}</div>}
    <section className="bg-white border border-secondary-200 rounded-xl shadow-sm overflow-hidden">
      <div className="p-4 border-b flex flex-wrap gap-3"><label className="relative flex-1 min-w-60"><Search size={16} className="absolute left-3 top-3 text-secondary-400"/><input className="w-full pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search template name or subject…"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>ACTIVE</option><option>INACTIVE</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
      {loading?<p className="p-8 text-center text-secondary-500">Loading templates…</p>:templates.length===0?<p className="p-8 text-center text-secondary-500">No email templates match these filters.</p>:<div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Template</th><th>Category</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{templates.map(t=><tr key={t.id}><td><strong>{t.templateName}</strong><small className="block text-secondary-500 mt-1">{t.subject}</small></td><td>{t.category}</td><td><button className={`badge ${t.status==='ACTIVE'?'badge-success':'badge-secondary'}`} onClick={()=>action(()=>api.patch(`/email/templates/${t.id}/status`,{status:t.status==='ACTIVE'?'INACTIVE':'ACTIVE'}),'Template status updated')}>{t.status}</button></td><td><span>{t.updatedBy||t.createdBy||'CRM user'}</span><small className="block text-secondary-500">{new Date(t.updatedAt||t.createdAt).toLocaleString('en-IN')}</small></td><td><div className="flex gap-1"><button className="icon-btn" title="Edit" onClick={()=>setEditing({...t})}><Pencil size={16}/></button><button className="icon-btn" title="Duplicate" onClick={()=>action(()=>api.post(`/email/templates/${t.id}/duplicate`,{}),'Template duplicated')}><Copy size={16}/></button><button className="icon-btn text-red-600" title="Delete" onClick={()=>confirm(`Delete ${t.templateName}?`)&&action(()=>api.delete(`/email/templates/${t.id}`),'Template deleted')}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}
    </section>
    {editing&&<TemplateEditor initial={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);onMessage?.({type:'success',text:'Email template saved'});load();}}/>}
  </main>;
}

function TemplateEditor({initial,onClose,onSaved}){
  const [form,setForm]=useState(initial),[error,setError]=useState(''),[saving,setSaving]=useState(false),[focus,setFocus]=useState('body');
  const editor=useRef(null); const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  useEffect(()=>{if(editor.current)editor.current.innerHTML=form.bodyHtml||'';},[]);
  const command=(name,value=null)=>{editor.current?.focus();document.execCommand(name,false,value);set('bodyHtml',editor.current?.innerHTML||'');};
  const insertVariable=name=>{const token=`{{${name}}}`;if(focus==='subject'){const input=document.getElementById('email-template-subject');const start=input?.selectionStart??form.subject.length;set('subject',form.subject.slice(0,start)+token+form.subject.slice(start));setTimeout(()=>input?.focus(),0);}else{editor.current?.focus();document.execCommand('insertText',false,token);set('bodyHtml',editor.current?.innerHTML||'');}};
  const save=async()=>{setSaving(true);setError('');try{const payload={...form,bodyHtml:editor.current?.innerHTML||form.bodyHtml};if(form.id)await api.put(`/email/templates/${form.id}`,payload);else await api.post('/email/templates',payload);onSaved();}catch(e){setError(e.message);}finally{setSaving(false);}};
  return <><div className="fixed inset-0 bg-black/40 z-40" onClick={onClose}/><section className="fixed z-50 inset-y-0 right-0 w-full max-w-3xl bg-white shadow-2xl flex flex-col" role="dialog"><header className="p-5 border-b flex justify-between"><div><h2 className="text-xl font-bold">{form.id?'Edit':'Create'} Email Template</h2><p className="text-sm text-secondary-500">Design the subject and email body.</p></div><button className="icon-btn" onClick={onClose}><X/></button></header><div className="p-5 overflow-y-auto space-y-5 flex-1">{error&&<div className="p-3 bg-red-50 text-red-700 rounded-lg">{error}</div>}<div className="grid md:grid-cols-2 gap-4"><Field label="Template Name *"><input value={form.templateName} onChange={e=>set('templateName',e.target.value)}/></Field><Field label="Category *"><select value={form.category} onChange={e=>set('category',e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field></div><Field label="Subject *"><input id="email-template-subject" value={form.subject} onFocus={()=>setFocus('subject')} onChange={e=>set('subject',e.target.value)}/></Field><Field label="Status"><select value={form.status} onChange={e=>set('status',e.target.value)}><option>ACTIVE</option><option>INACTIVE</option></select></Field><div><label className="text-sm font-semibold">Email Body *</label><div className="flex flex-wrap gap-1 border rounded-t-lg p-2 bg-secondary-50"><Tool onClick={()=>command('bold')} label="B"/><Tool onClick={()=>command('italic')} label="I"/><Tool onClick={()=>command('underline')} label="U"/><Tool onClick={()=>command('formatBlock','h2')} label="Heading"/><Tool onClick={()=>command('insertUnorderedList')} label="• List"/><Tool onClick={()=>command('insertOrderedList')} label="1. List"/><Tool onClick={()=>command('justifyLeft')} label="Left"/><Tool onClick={()=>command('justifyCenter')} label="Centre"/><Tool onClick={()=>{const url=prompt('Link URL');if(url)command('createLink',url)}} label="Link"/></div><div ref={editor} contentEditable suppressContentEditableWarning onFocus={()=>setFocus('body')} onInput={e=>set('bodyHtml',e.currentTarget.innerHTML)} className="min-h-64 border border-t-0 rounded-b-lg p-4 outline-none prose max-w-none"/></div><div><h3 className="text-sm font-bold mb-2">Variables / Merge Fields</h3><p className="text-xs text-secondary-500 mb-2">Click to insert into the currently selected subject or body.</p><div className="flex flex-wrap gap-2">{variables.map(v=><button key={v} className="px-2.5 py-1.5 rounded-md bg-primary-50 text-primary-700 text-xs font-semibold" onClick={()=>insertVariable(v)}>{`{{${v}}}`}</button>)}</div></div></div><footer className="p-5 border-t flex justify-end gap-3"><button className="btn btn-outline" onClick={onClose}>Cancel</button><button className="btn btn-primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save Template'}</button></footer></section></>;
}
function Tool({label,onClick}){return <button type="button" className="px-2.5 py-1 rounded border bg-white text-xs font-semibold" onMouseDown={e=>{e.preventDefault();onClick();}}>{label}</button>}
function Field({label,children}){return <label className="block space-y-1.5 text-sm font-semibold">{label}{children}</label>}
