import { useEffect,useMemo,useState } from 'react';
import { Copy,ExternalLink,Link2,Plus,RefreshCw,Trash2,X } from 'lucide-react';
import { api } from '../api.js';
import './JodoPaymentLinksSettings.css';

const empty={branchId:'',environment:'production',leadId:'',name:'',phone:'',email:'',studentName:'',identifier:'',customIdentifier:'',grade:'',dateOfBirth:'',academicYearStart:new Date().getFullYear(),academicYearEnd:new Date().getFullYear()+1,newAdmission:true,expiresAt:'',details:[{componentType:'Payable Amount',amount:''}],notes:[]};
const money=value=>`₹${Number(value||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function JodoPaymentLinksSettings({onMessage}){
  const [links,setLinks]=useState([]),[branches,setBranches]=useState([]),[form,setForm]=useState(empty),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
  const notify=(type,text)=>onMessage?.({type,text});
  async function load(){const [linkResult,branchResult]=await Promise.all([api('/jodo/payment-links'),api('/jodo/payment-links/branches')]);setLinks(linkResult.data||[]);setBranches(branchResult.data||[]);}
  useEffect(()=>{load().catch(error=>notify('error',error.message));},[]);
  const visible=useMemo(()=>links.filter(item=>`${item.orderId} ${item.payerName} ${item.payerPhone} ${item.studentName||''} ${item.branchName}`.toLowerCase().includes(search.toLowerCase().trim())),[links,search]);
  const patch=value=>setForm(current=>({...current,...value}));
  function updateDetail(index,key,value){patch({details:form.details.map((item,i)=>i===index?{...item,[key]:value}:item)});}
  async function create(event){event.preventDefault();setBusy(true);try{const result=await api.post('/jodo/payment-links',form);await navigator.clipboard?.writeText(result.data.redirectUrl);notify('success','Payment link created and copied');setOpen(false);setForm(empty);await load();}catch(error){notify('error',error.message);}finally{setBusy(false);}}
  async function refresh(item){setBusy(true);try{await api(`/jodo/payment-links/${item.id}`);notify('success','Payment status refreshed');await load();}catch(error){notify('error',error.message);}finally{setBusy(false);}}
  async function cancel(item){if(!window.confirm(`Cancel payment link ${item.orderId}? The payer will no longer be able to use it.`))return;setBusy(true);try{await api.delete(`/jodo/payment-links/${item.id}`);notify('success','Payment link cancelled');await load();}catch(error){notify('error',error.message);}finally{setBusy(false);}}
  return <main className="jodo-links">
    <header><div><span>JODO PAY</span><h1>Payment links</h1><p>Create shareable hosted payment links, check payment status and cancel unpaid links.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={16}/>Create payment link</button></header>
    <section className="jodo-toolbar"><input placeholder="Search payer, student, phone or order ID" value={search} onChange={event=>setSearch(event.target.value)}/><button onClick={()=>load().catch(error=>notify('error',error.message))}><RefreshCw size={16}/>Refresh</button></section>
    <section className="jodo-table"><div className="jodo-row head"><span>Payer / student</span><span>Branch</span><span>Amount</span><span>Status</span><span>Created</span><span>Actions</span></div>{visible.map(item=><div className="jodo-row" key={item.id}><span><strong>{item.payerName}</strong><small>{item.studentName||item.payerPhone}</small><code>{item.orderId}</code></span><span>{item.branchName}<small>{item.environment.toUpperCase()}</small></span><span><strong>{money(item.amount)}</strong>{item.expiresAt&&<small>Expires {new Date(item.expiresAt).toLocaleString('en-IN')}</small>}</span><span><em className={`status ${item.status}`}>{item.status}</em>{item.transactionId&&<small>{item.transactionId}</small>}</span><span>{new Date(item.createdAt).toLocaleString('en-IN')}</span><span className="row-actions"><button title="Copy link" onClick={()=>navigator.clipboard.writeText(item.redirectUrl).then(()=>notify('success','Payment link copied'))}><Copy size={15}/></button><a title="Open payment page" href={item.redirectUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/></a><button title="Refresh from Jodo" disabled={busy} onClick={()=>refresh(item)}><RefreshCw size={15}/></button>{!['paid','settled','cancelled'].includes(String(item.status).toLowerCase())&&<button title="Cancel payment link" disabled={busy} onClick={()=>cancel(item)}><Trash2 size={15}/></button>}</span></div>)}{!visible.length&&<div className="empty"><Link2/><strong>No payment links found</strong><span>Create a link after configuring Jodo credentials for a branch.</span></div>}</section>
    {open&&<div className="jodo-modal"><section><header><div><h2>Create Jodo payment link</h2><p>Required fields follow Jodo's Payment Link API.</p></div><button onClick={()=>setOpen(false)}><X/></button></header><form onSubmit={create}>
      <label>Branch *<select required value={form.branchId} onChange={e=>patch({branchId:e.target.value})}><option value="">Select configured branch</option>{branches.map(branch=><option key={branch.id} disabled={!branch.enabled||!branch.configured} value={branch.id}>{branch.name}{!branch.enabled||!branch.configured?' · Jodo not configured':''}</option>)}</select></label>
      <label>Environment<select value={form.environment} onChange={e=>patch({environment:e.target.value})}><option value="production">Production</option><option value="uat">UAT / Sandbox</option></select></label>
      <label>Payer name *<input required value={form.name} onChange={e=>patch({name:e.target.value})}/></label><label>Phone *<input required inputMode="numeric" value={form.phone} onChange={e=>patch({phone:e.target.value})}/></label><label>Email *<input required type="email" value={form.email} onChange={e=>patch({email:e.target.value})}/></label><label>Student name<input value={form.studentName} onChange={e=>patch({studentName:e.target.value})}/></label>
      <label>CRM lead number<input value={form.leadId} onChange={e=>patch({leadId:e.target.value})} placeholder="Optional, e.g. ADM-2026-000123"/></label><label>Student identifier<input value={form.identifier} onChange={e=>patch({identifier:e.target.value})}/></label><label>Grade identifier<input value={form.grade} onChange={e=>patch({grade:e.target.value})}/></label><label>Date of birth<input type="date" value={form.dateOfBirth} onChange={e=>patch({dateOfBirth:e.target.value})}/></label>
      <label>Academic year start<input type="number" min="2000" max="2200" value={form.academicYearStart} onChange={e=>patch({academicYearStart:e.target.value})}/></label><label>Academic year end<input type="number" min="2000" max="2200" value={form.academicYearEnd} onChange={e=>patch({academicYearEnd:e.target.value})}/></label><label>Expires at<input type="datetime-local" value={form.expiresAt} onChange={e=>patch({expiresAt:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.newAdmission} onChange={e=>patch({newAdmission:e.target.checked})}/>New admission</label>
      <fieldset><legend>Payment components *</legend>{form.details.map((item,index)=><div key={index}><input required placeholder="Component type" value={item.componentType} onChange={e=>updateDetail(index,'componentType',e.target.value)}/><input required type="number" min="0.01" step="0.01" placeholder="Amount" value={item.amount} onChange={e=>updateDetail(index,'amount',e.target.value)}/>{form.details.length>1&&<button type="button" onClick={()=>patch({details:form.details.filter((_,i)=>i!==index)})}><X size={15}/></button>}</div>)}<button type="button" onClick={()=>patch({details:[...form.details,{componentType:'',amount:''}]})}><Plus size={15}/>Add component</button><strong>Total: {money(form.details.reduce((sum,item)=>sum+Number(item.amount||0),0))}</strong></fieldset>
      <fieldset><legend>Metadata notes</legend>{form.notes.map((item,index)=><div key={index}><input placeholder="Key" value={item.key} onChange={e=>patch({notes:form.notes.map((note,i)=>i===index?{...note,key:e.target.value}:note)})}/><input placeholder="Value" value={item.value} onChange={e=>patch({notes:form.notes.map((note,i)=>i===index?{...note,value:e.target.value}:note)})}/><button type="button" onClick={()=>patch({notes:form.notes.filter((_,i)=>i!==index)})}><X size={15}/></button></div>)}<button type="button" onClick={()=>patch({notes:[...form.notes,{key:'',value:''}]})}><Plus size={15}/>Add note</button></fieldset>
      <footer><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create and copy link'}</button></footer>
    </form></section></div>}
  </main>;
}
