import { useEffect, useState } from 'react';
import { Activity, CheckCircle2, PhoneCall, RefreshCw, Save } from 'lucide-react';
import { api } from '../api.js';
import './CallerDeskSettings.css';

const array=value=>Array.isArray(value)?value:Array.isArray(value?.data)?value.data:Array.isArray(value?.results)?value.results:[];
export default function SmartfloSettings({onMessage}){
  const [form,setForm]=useState({accountName:'Tata Smartflo',email:'',password:'',permanentToken:'',clearPermanentToken:false,callingMode:'AGENT_FIRST',supportApiKey:'',clearSupportApiKey:false,defaultDid:'',defaultDepartmentId:'',callTimeout:300,customerRingTimeout:30,recordCalls:true,isActive:true});
  const [numbers,setNumbers]=useState([]),[departments,setDepartments]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [testNumber,setTestNumber]=useState(''),[testResult,setTestResult]=useState(null);
  const notify=(text,type='success')=>{setError(type==='error'?text:'');onMessage?.({type,text});};
  async function load(){const result=await api('/smartflo/config');setForm(current=>({...current,...result.data,password:'',permanentToken:'',clearPermanentToken:false,supportApiKey:'',clearSupportApiKey:false}));if(result.data.configured){const numberResult=await api('/smartflo/numbers');setNumbers(array(numberResult.data));const departmentResult=await api('/smartflo/departments');setDepartments(array(departmentResult.data));}}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function save(e){e.preventDefault();setBusy(true);try{const result=await api.put('/smartflo/config',form);notify(result.message||'Smartflo configuration saved');await load();}catch(e){notify(e.message,'error');}finally{setBusy(false);}}
  async function test(){setBusy(true);try{await api.post('/smartflo/test',{});notify('Smartflo connection is working');await load();}catch(e){notify(e.message,'error');}finally{setBusy(false);}}
  async function testCall(){setBusy(true);setTestResult(null);try{const result=await api.post('/smartflo/test-call',{customerNumber:testNumber});setTestResult(result.data);notify('Smartflo test call initiated');}catch(e){setTestResult({status:'Failed',error:e.message,callingMode:form.callingMode,customerNumber:testNumber});notify(e.message,'error');}finally{setBusy(false);}}
  return <div className="callerdesk-settings"><header className="page-action-row"><button className="secondary" onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={16}/>Refresh</button></header>{error&&<div className="callerdesk-error">{error}</div>}
    <section className="callerdesk-guide"><strong>Configuration guide</strong><span><b>1</b>Save credentials/token</span><span><b>2</b>Test DID, IVR and user access</span><span><b>3</b>Map branch DIDs and IVRs</span><span><b>4</b>Map agents in User Management</span></section>
    <section className="callerdesk-card"><div className="section-title"><PhoneCall/><div><h2>Account setup</h2><p>Credentials and tokens are encrypted and never returned to the browser. This account belongs to the business unit selected above — another unit configures its own.</p></div>{form.configured&&<span className="connected"><CheckCircle2/>Connected</span>}</div><form className="callerdesk-grid" onSubmit={save}>
      <label>Account name<small>Friendly name inside CRM</small><input value={form.accountName||''} onChange={e=>setForm({...form,accountName:e.target.value})}/></label>
      <label>Smartflo login email<small>Use with password, or provide an API access token instead</small><input type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label>
      <label>Password<small>Creates a one-hour JWT token</small><input type="password" placeholder={form.hasPassword?'Leave blank to keep current password':'Smartflo password'} value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})}/></label>
      <label>Smartflo API access token<small>From API Connect → API Tokens. Do not use a Click-to-Call Support API key.</small><input type="password" placeholder={form.hasPermanentToken?'Leave blank to keep current API token':'Paste Smartflo API access token'} value={form.permanentToken||''} onChange={e=>setForm({...form,permanentToken:e.target.value})}/></label>
      {form.hasPermanentToken&&<label className="wide check-option"><input type="checkbox" checked={form.clearPermanentToken} onChange={e=>setForm({...form,clearPermanentToken:e.target.checked,permanentToken:e.target.checked?'':form.permanentToken})}/>Remove the saved API token and use login email/password</label>}
      <label>Default DID<small>Fallback when a branch has no Smartflo DID</small><select value={form.defaultDid||''} onChange={e=>setForm({...form,defaultDid:e.target.value})}><option value="">Select My Number</option>{form.defaultDid&&!numbers.some(n=>String(n.did||n.number||n.did_number)===form.defaultDid)&&<option value={form.defaultDid}>{form.defaultDid} (saved)</option>}{numbers.map((n,i)=><option key={n.id||i} value={n.did||n.number||n.did_number}>{n.did||n.number||n.did_number||n.name}{n.destination_name?` · ${n.destination_name}`:''}</option>)}</select></label>
      <label>Default department<small>Fallback routing department</small><select value={form.defaultDepartmentId||''} onChange={e=>setForm({...form,defaultDepartmentId:e.target.value})}><option value="">No default department</option>{departments.map((d,i)=><option key={d.id||i} value={d.id}>{d.name||d.department_name}</option>)}</select></label>
      <label className="wide check-option"><input type="checkbox" checked={form.recordCalls!==false} onChange={e=>setForm({...form,recordCalls:e.target.checked})}/>Capture call recordings in CRM <small>Stores recording links returned by Tata. Provider-side recording must be enabled in Smartflo.</small></label>
      <div className="wide actions"><button type="button" className="secondary" disabled={!form.configured||busy} onClick={test}><Activity size={16}/>Test connection</button><button className="primary" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save configuration'}</button></div>
    </form>{form.webhookPath&&<div className="webhook"><strong>Call-event webhook</strong><code>{location.origin.replace(/:\d+$/,':3001')}{form.webhookPath}</code><small>Configure this public HTTPS URL in Smartflo to capture outcomes, durations and recordings.</small></div>}</section>
    <section className="callerdesk-card"><div className="section-title"><PhoneCall/><div><h2>Calling configuration</h2><p>Select one calling flow for every Smartflo call made throughout the CRM.</p></div></div><div className="calling-mode-options">
      <label className={form.callingMode==='AGENT_FIRST'?'selected':''}><input type="radio" name="smartfloCallingMode" checked={form.callingMode==='AGENT_FIRST'} onChange={()=>setForm({...form,callingMode:'AGENT_FIRST'})}/><span><strong>Agent First – Standard Click to Call</strong><small>Smartflo calls the counsellor first. After the counsellor answers, it calls the customer.</small></span></label>
      <label className={form.callingMode==='CUSTOMER_FIRST'?'selected':''}><input type="radio" name="smartfloCallingMode" checked={form.callingMode==='CUSTOMER_FIRST'} onChange={()=>setForm({...form,callingMode:'CUSTOMER_FIRST'})}/><span><strong>Customer First – Click to Call Support</strong><small>Smartflo calls the customer first. After the customer answers, it calls the destination configured against the Support API key.</small></span></label>
    </div><form className="callerdesk-grid calling-config-grid" onSubmit={save}>
      {form.callingMode==='CUSTOMER_FIRST'&&<><label className="wide">Click-to-Call Support API key *<small>Generated under Click to Call Support API Tokens. This is separate from the API Connect bearer token.</small><input type="password" required={!form.hasSupportApiKey} placeholder={form.hasSupportApiKey?'Leave blank to keep current Support API key':'Paste Support API key'} value={form.supportApiKey||''} onChange={e=>setForm({...form,supportApiKey:e.target.value,clearSupportApiKey:false})}/></label>{form.hasSupportApiKey&&<label className="wide check-option"><input type="checkbox" checked={form.clearSupportApiKey} onChange={e=>setForm({...form,clearSupportApiKey:e.target.checked,supportApiKey:e.target.checked?'':form.supportApiKey})}/>Remove the saved Support API key</label>}</>}
      <label>Maximum connected-call duration<small>30–7200 seconds</small><input type="number" min="30" max="7200" value={form.callTimeout||300} onChange={e=>setForm({...form,callTimeout:Number(e.target.value)})}/></label>
      {form.callingMode==='CUSTOMER_FIRST'&&<label>Customer ring timeout<small>10–30 seconds</small><input type="number" min="10" max="30" value={form.customerRingTimeout||30} onChange={e=>setForm({...form,customerRingTimeout:Number(e.target.value)})}/></label>}
      <div className="wide actions"><button className="primary" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save changes'}</button></div>
    </form>
    <div className="test-call-panel"><div><strong>Test the saved calling mode</strong><small>Places a real call and stores it in CRM call activity without exposing credentials.</small></div><div className="test-call-controls"><input inputMode="numeric" placeholder="Test customer number" value={testNumber} onChange={e=>setTestNumber(e.target.value.replace(/\D/g,'').slice(0,13))}/><button type="button" className="secondary" disabled={busy||!form.configured||testNumber.length<10} onClick={testCall}><PhoneCall size={16}/>Test call</button></div>{testResult&&<dl className="test-call-result"><div><dt>Calling mode</dt><dd>{testResult.callingModeLabel||testResult.callingMode}</dd></div><div><dt>Customer number</dt><dd>{testResult.customerNumber}</dd></div><div><dt>API</dt><dd>{testResult.apiEndpoint||'Not initiated'}</dd></div><div><dt>Status</dt><dd>{testResult.status}</dd></div>{testResult.providerMessage&&<div><dt>Provider response</dt><dd>{testResult.providerMessage}</dd></div>}{testResult.error&&<div><dt>Error</dt><dd>{testResult.error}</dd></div>}</dl>}</div>
    </section>
  </div>;
}
